name: Patch Release Request
description: Request the publication of a new patch release.
title: Release vMajor.Minor.Patch[ | Release Name]
labels: [ "release", "release:patch" ]
assignees: []
body:
  - type: textarea
    attributes:
      label: Opening Remarks
      description: A few remarks to open the announcement of a release.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Bug Fixes
      description: A list of bugs fixed in the release.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Closing Remarks
      description: A few remarks to close the announcement of a release.
    validations:
      required: false
