name: Release Request
description: A GitHub action which introduces and provides tooling dealing with release requests.

inputs:
  discussion-category-name:
    default: ''
    description: Specifies the name of the category to create a discussion in when the release is published.
    required: false
  draft:
    default: 'true'
    description: If true, the release created will be drafted rather than published.
    required: false
  generate-release-notes:
    default: 'false'
    description: If true, the release name and notes will be generated if they were unspecified at the time of publish.
    required: false
  make-latest:
    default: 'legacy'
    description: Specifies how the latest release is determined. For more information, see https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release.
    required: false
  release-request-label:
    default: 'release'
    description: The label that identifies release requests.
    required: false
  token:
    default: ${{ github.token }}
    description: The personal access token used to access the GitHub API.
    required: false

outputs:
  release-tag:
    description: The tag of the release.
  release-title:
    description: The title of the release.

runs:
  using: 'node24'
  main: 'dist/index.js'
