name: Validate Release Request
run-name: Validate Release Request

on:
  pull_request:
    types:
      - edited
      - opened

  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  check_rr:
    name: Validate Release Request
    runs-on: ubuntu-22.04
    timeout-minutes: 2

    steps:
      - name: Validate Release Request
        env:
          RR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ ! $RR_TITLE =~ ^Release (v[0-9]+\.[0-9]+(\.[0-9]+(\.[0-9]+)?)?(-[a-zA-Z0-9_]+)?)$ ]] ; then
            echo 'Exiting. Release request title does not match format `v<Major>.<Minor>[.<Patch>[.<Build>]][-<Suffix>]`.' | tee -a "$GITHUB_STEP_SUMMARY"
            exit 1
          fi
